name_of_the_user = input("Enter your name: ")
length_of_name =len(name_of_the_user)
print(type("Number of latters in your name: "))
print(type(length_of_name))
print("number of latters in your name: "+ str(length_of_name))
ram= input("Enter your ram: ")
length=len(ram)
print(type(ram))
print(type(length))
print("number of letters in your name: "+ str(length)